version: "3"
services:
    www:
        build:
            dockerfile: Dockerfile
        ports:
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0.16
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: klikgss
            MYSQL_PASSWORD: qwe-123-123
            MYSQL_ROOT_PASSWORD: qwe-123-123
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: saka
            MORE_DATABASES: cdulab muamkm dsm detasales hris nuanzaceramic nuansafood yski yski_usek 
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - ./db:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.8
        links:
            - db:db
        ports:
            - "8000:80"
        environment:
            MYSQL_USER: klikgss
            MYSQL_PASSWORD: qwe-123-123
            MYSQL_ROOT_PASSWORD: qwe-123-123
#volumes:
#    persistent: